sudo: required

dist: trusty

language: node_js

node_js:
  - "7.9.0"

before_install:
  - docker pull ethcore/parity:beta
  - docker run -v /home/travis/build/hai-ko/CITest/testchaindata:/testchaindata -ti ethcore/parity:beta account import /testchaindata/keys/ --chain dev --base-path /testchaindata/temp/
  - docker run -v /home/travis/build/hai-ko/CITest/testchaindata:/testchaindata -dti --network="host" -p 8180:8180 -p 8545:8545 -p 30303:30303 ethcore/parity:beta --chain /testchaindata/chain.json --no-ui --unlock 0x1ee4571be14b85107f8ce8a925bba278b75716d5 --password /testchaindata/password.txt --reseal-min-period 0 --gasprice 0 --base-path /testchaindata/temp/

install:
  - npm install
  - docker ps -a  

services:
  - postgresql
  - docker