sudo: required

dist: trusty

language: node_js

node_js:
  - "7.9.0"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq
  - docker pull ethcore/parity:beta
  - ls testchaindata/keys/
  - docker run -ti ethcore/parity:beta account import /home/travis/build/hai-ko/CITest/testchaindata/keys/ --chain dev
  - docker run -ti -p 8180:8180 -p 8545:8545 -p 30303:30303 ethcore/parity:beta daemon parity.pid --chain testchaindata/chain.json --no-ui --unlock 0x1ee4571be14b85107f8ce8a925bba278b75716d5 --password testchaindata/password.txt --reseal-min-period 0 --gasprice 0
  - docker ps -a


install:
  - npm install
  

services:
  - postgresql
  - docker