sudo: required

dist: trusty

language: node_js

node_js:
  - "7.9.0"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq
  - docker pull ethcore/parity:stable
  - docker run -ti -p 8180:8180 -p 8545:8545 -p 30303:30303 ethcore/parity:stable daemon parity.pid --chain dev --no-ui
  - docker ps -a

install:
  - npm install
  

services:
  - postgresql
  - docker