sudo: required

dist: trusty

language: node_js

node_js:
  - "7.9.0"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq
  - sudo apt-get install -y -qq build-essential git unzip wget ntp cloud-utils
  - sudo curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y
  - cargo install --git https://github.com/paritytech/parity.git parity

install:
  - npm install
  - npm run testrpc

services:
  - postgresql